name: Check for TODO

on:
  pull_request:
    branches:
      - master

jobs:
  todo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Find TODOs
        run: |
          if grep -rnw 'TODO' .; then
            echo "Found TODOs. Blocking merge."
            exit 1
          fi
